const themes = {
  // Dark Themes
  darkRed: {
    "--bg-primary": "#212121",
    "--bg-secondary": "#171717",
    "--bg-tertiary": "#2d2d2d",
    "--foreground": "#ffffff",
    "--foreground-secondary": "#a6a6a6",
    "--foreground-tertiary": "#767676",
    "--foreground-quaternary": "#ffffff",
    "--foreground-light-bg": "#2d2d2d",
    "--foreground-primary-bg": "#ffffff",
    "--theme-primary": "#e53637",
    "--border-primary": "#585858",
    "--border-secondary": "#2a2a2a",
    "--border-tertiary": "#1d1d1d",
    "--button-primary-bg": "#e53637",
    "--button-primary-text": "#ffffff",
    "--button-secondary-bg": "#ff7f50",
    "--button-secondary-text": "#181818",
    "--button-hover-bg": "#c72f2f",
    "--button-hover-text": "#ffffff",
  },

  darkPurple: {
    "--bg-primary": "#212121",
    "--bg-secondary": "#171717",
    "--bg-tertiary": "#2d2d2d",
    "--foreground": "#ffffff",
    "--foreground-secondary": "#a6a6a6",
    "--foreground-tertiary": "#767676",
    "--foreground-quaternary": "#ffffff",
    "--foreground-light-bg": "#2d2d2d",
    "--foreground-primary-bg": "#ffffff",
    "--theme-primary": "#8B5CF6",
    "--border-primary": "#585858",
    "--border-secondary": "#2a2a2a",
    "--border-tertiary": "#1d1d1d",
    "--theme-primary": "#8B5CF6",
    "--button-primary-bg": "#000000",
    "--button-primary-text": "#ffffff",
    "--button-secondary-bg": "#6d28d9",
    "--button-secondary-text": "#ffffff",
    "--button-hover-bg": "#7c3aed",
    "--button-hover-text": "#ffffff",
  },

  darkGreen: {
    "--bg-primary": "#212121",
    "--bg-secondary": "#171717",
    "--bg-tertiary": "#2d2d2d",
    "--foreground": "#ffffff",
    "--foreground-secondary": "#a6a6a6",
    "--foreground-tertiary": "#767676",
    "--foreground-quaternary": "#ffffff",
    "--foreground-light-bg": "#000000",
    "--foreground-primary-bg": "#000000",
    "--theme-primary": "#10B981",
    "--border-primary": "#585858",
    "--border-secondary": "#2a2a2a",
    "--border-tertiary": "#1d1d1d",
    "--theme-primary": "#10B981",
    "--button-primary-bg": "#10B981",
    "--button-primary-text": "#ffffff",
    "--button-secondary-bg": "#047857",
    "--button-secondary-text": "#ffffff",
    "--button-hover-bg": "#059669",
    "--button-hover-text": "#ffffff",
  },

  darkMagento: {
    "--bg-primary": "#212121",
    "--bg-secondary": "#171717",
    "--bg-tertiary": "#2d2d2d",
    "--foreground": "#ffffff",
    "--foreground-secondary": "#a6a6a6",
    "--foreground-tertiary": "#767676",
    "--foreground-quaternary": "#ffffff",
    "--foreground-light-bg": "#000000",
    "--foreground-primary-bg": "#000000",
    "--theme-primary": "#D946EF",
    "--border-primary": "#585858",
    "--border-secondary": "#2a2a2a",
    "--border-tertiary": "#1d1d1d",
    "--theme-primary": "#D946EF",
    "--button-primary-bg": "#D946EF",
    "--button-primary-text": "#ffffff",
    "--button-secondary-bg": "#a21caf",
    "--button-secondary-text": "#ffffff",
    "--button-hover-bg": "#c026d3",
    "--button-hover-text": "#ffffff",
  },

  darkVoilet: {
    "--bg-primary": "#212121",
    "--bg-secondary": "#171717",
    "--bg-tertiary": "#2d2d2d",
    "--foreground": "#ffffff",
    "--foreground-secondary": "#a6a6a6",
    "--foreground-tertiary": "#767676",
    "--foreground-quaternary": "#ffffff",
    "--foreground-light-bg": "#2d2d2d",
    "--foreground-primary-bg": "#ffffff",
    "--theme-primary": "#7C3AED",
    "--border-primary": "#585858",
    "--border-secondary": "#2a2a2a",
    "--border-tertiary": "#1d1d1d",
    "--theme-primary": "#7C3AED",
    "--button-primary-bg": "#7C3AED",
    "--button-primary-text": "#ffffff",
    "--button-secondary-bg": "#5b21b6",
    "--button-secondary-text": "#ffffff",
    "--button-hover-bg": "#6d28d9",
    "--button-hover-text": "#ffffff",
  },

  // Light Themes
  lightRed: {
    "--bg-primary": "#ffffff",
    "--bg-secondary": "#f8f8f8",
    "--bg-tertiary": "#f0f0f0",
    "--foreground": "#212121",
    "--foreground-secondary": "#2d2d2d",
    "--foreground-tertiary": "#3a3a3a",
    "--foreground-quaternary": "#000000",
    "--foreground-light-bg": "#ffffff",
    "--foreground-primary-bg": "#ffffff",
    "--theme-primary": "#e53637",
    "--border-primary": "#d4d4d4",
    "--border-secondary": "#c0c0c0",
    "--border-tertiary": "#a8a8a8",
    "--theme-primary": "#e53637",
    "--button-primary-bg": "#e53637",
    "--button-primary-text": "#ffffff",
    "--button-secondary-bg": "#ff7f50",
    "--button-secondary-text": "#181818",
    "--button-hover-bg": "#c72f2f",
    "--button-hover-text": "#ffffff",
  },

  lightPurple: {
    "--bg-primary": "#ffffff",
    "--bg-secondary": "#f8f8f8",
    "--bg-tertiary": "#f0f0f0",
    "--foreground": "#212121",
    "--foreground-secondary": "#2d2d2d",
    "--foreground-tertiary": "#3a3a3a",
    "--foreground-quaternary": "#000000",
    "--foreground-light-bg": "#ffffff",
    "--foreground-primary-bg": "#ffffff",
    "--theme-primary": "#8B5CF6",
    "--border-primary": "#d4d4d4",
    "--border-secondary": "#c0c0c0",
    "--border-tertiary": "#a8a8a8",
    "--theme-primary": "#8B5CF6",
    "--button-primary-bg": "#8B5CF6",
    "--button-primary-text": "#ffffff",
    "--button-secondary-bg": "#6d28d9",
    "--button-secondary-text": "#ffffff",
    "--button-hover-bg": "#7c3aed",
    "--button-hover-text": "#ffffff",
  },

  lightGreen: {
    "--bg-primary": "#ffffff",
    "--bg-secondary": "#f8f8f8",
    "--bg-tertiary": "#f0f0f0",
    "--foreground": "#212121",
    "--foreground-secondary": "#2d2d2d",
    "--foreground-tertiary": "#3a3a3a",
    "--foreground-quaternary": "#000000",
    "--foreground-light-bg": "#ffffff",
    "--foreground-primary-bg": "#ffffff",
    "--theme-primary": "#10B981",
    "--border-primary": "#d4d4d4",
    "--border-secondary": "#c0c0c0",
    "--border-tertiary": "#a8a8a8",
    "--theme-primary": "#10B981",
    "--button-primary-bg": "#10B981",
    "--button-primary-text": "#ffffff",
    "--button-secondary-bg": "#047857",
    "--button-secondary-text": "#ffffff",
    "--button-hover-bg": "#059669",
    "--button-hover-text": "#ffffff",
  },

  lightMagento: {
    "--bg-primary": "#ffffff",
    "--bg-secondary": "#f8f8f8",
    "--bg-tertiary": "#f0f0f0",
    "--foreground": "#212121",
    "--foreground-secondary": "#2d2d2d",
    "--foreground-tertiary": "#3a3a3a",
    "--foreground-quaternary": "#000000",
    "--foreground-light-bg": "#ffffff",
    "--foreground-primary-bg": "#ffffff",
    "--theme-primary": "#D946EF",
    "--border-primary": "#d4d4d4",
    "--border-secondary": "#c0c0c0",
    "--border-tertiary": "#a8a8a8",
    "--theme-primary": "#D946EF",
    "--button-primary-bg": "#D946EF",
    "--button-primary-text": "#ffffff",
    "--button-secondary-bg": "#a21caf",
    "--button-secondary-text": "#ffffff",
    "--button-hover-bg": "#c026d3",
    "--button-hover-text": "#ffffff",
  },

  lightViolet: {
    "--bg-primary": "#ffffff",
    "--bg-secondary": "#f8f8f8",
    "--bg-tertiary": "#f0f0f0",
    "--foreground": "#212121",
    "--foreground-secondary": "#2d2d2d",
    "--foreground-tertiary": "#3a3a3a",
    "--foreground-quaternary": "#000000",
    "--foreground-light-bg": "#ffffff",
    "--foreground-primary-bg": "#ffffff",
    "--theme-primary": "#7C3AED",
    "--border-primary": "#d4d4d4",
    "--border-secondary": "#c0c0c0",
    "--border-tertiary": "#a8a8a8",
    "--theme-primary": "#7C3AED",
    "--button-primary-bg": "#7C3AED",
    "--button-primary-text": "#ffffff",
    "--button-secondary-bg": "#5b21b6",
    "--button-secondary-text": "#ffffff",
    "--button-hover-bg": "#6d28d9",
    "--button-hover-text": "#ffffff",
  },

  hybridSpecial: {
    "--bg-primary": "#0e0e0e" /* Deep Black */,
    "--bg-secondary": "#1a1a1a" /* Dark Gray */,
    "--bg-tertiary": "#222222" /* Slightly Lighter Gray */,

    "--foreground": "#e0e0e0" /* Light Gray for Text */,
    "--foreground-secondary": "#b0b0b0" /* Softer Gray */,
    "--foreground-tertiary": "#8c8c8c" /* Muted Gray */,
    "--foreground-quaternary": "#ffffff" /* White for Contrast */,
    "--foreground-light-bg": "#181818" /* Slightly Darker Gray */,
    "--foreground-primary-bg": "#000000" /* Pure Black for High Contrast */,

    "--theme-primary": "#2a8fcc" /* Vibrant Sky Blue */,
    "--theme-secondary": "#f4a261" /* Warm Orange */,
    "--theme-accent": "#e63946" /* Bold Red for Highlights */,

    "--border-primary": "#444444" /* Subtle Gray Borders */,
    "--border-secondary": "#666666" /* Medium Gray */,
    "--border-tertiary": "#888888" /* Light Gray */,

    "--button-primary-bg": "#2a8fcc" /* Sky Blue */,
    "--button-primary-text": "#ffffff" /* White Text on Primary Button */,

    "--button-secondary-bg": "#f4a261" /* Warm Orange */,
    "--button-secondary-text": "#181818" /* Dark Text on Secondary Button */,

    "--button-hover-bg": "#1f78b4" /* Slightly Darker Blue on Hover */,
    "--button-hover-text": "#ffffff" /* Keep White for Contrast */,
  },
};

export default themes;
